# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    identifier: nH3il4Pl
    url: /
    weight: 10
  - name: Papers
    identifier: bFzXjQYw
    url: /#papers
    weight: 20
  - name: Talks
    identifier: DhJYVji7
    url: /#talks
    weight: 30
  - name: News
    identifier: TbvoB75c
    url: /#news
    weight: 40
  - name: Experience
    identifier: G7CDSA3M
    url: experience/
    weight: 50
  - name: Outreach
    identifier: TjWRFpsM
    url: /projects/
    weight: 60
  - name: Courses
    identifier: laCyN1yW
    url: courses/
    weight: 70
  - name: Main
    identifier: main
    url: https://dreamome.com
    weight: 80
