hugoblox:
  schema: "2.0"
  identity:
    name: Timothy En Haw Chan
    type: person
    tagline: Biomedical Scientist
    description: Timothy En Haw Chan is a scientist working on understanding epigenetics in cancer and cell signaling.
  theme:
    mode: system
    pack: contrast
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: sans
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: Â© {year} {name}
  content:
    math:
      enable: false
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
